name: Build Kernel

on:
  push:
    branches:
      - bandido
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        bc bison build-essential ccache curl flex git \
        gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
        libssl-dev libncurses5-dev libncurses-dev \
        lzop python3 unzip zip wget

    - name: Download Android Clang
      run: |
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r487747c.tar.gz
        mkdir clang
        tar -xf clang-r487747c.tar.gz -C clang

    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$PWD/clang/bin:$PATH

        make O=out ARCH=arm64 r8q_eur_open_defconfig

        make -j$(nproc) \
        O=out \
        ARCH=arm64 \
        CC=clang \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: out/arch/arm64/boot/Image
